#!/usr/bin/env python

import datetime

import boto3
from boto3.dynamodb.conditions import Key

class DuhnList:
    def __init__(self, email):
        boto3.setup_default_session(profile_name='duhnit')
        dynamodb = boto3.resource('dynamodb')
        self.deeds_table = dynamodb.Table('deeds')
        self.email = email

    def deed_item_formatted_date(self, done_at):
        datetime_original_format = '%Y-%m-%d %H:%M:%S.%f'
        time = datetime.datetime.strptime(done_at, datetime_original_format)

        datetime_short_format = '%Y-%m-%d %H:%M'
        return time.strftime(datetime_short_format)

    def deed_list(self):
        response = self.deeds_table.query(
            KeyConditionExpression=Key('author-email').eq('julio@morgane.com'))

        items = sorted(response['Items'], key=lambda item: item['done-at'], reverse=True)
        for item in items:
            print(self.deed_item_formatted_date(item['done-at']), item['deed-type'].split('-')[0], item['deed'])

if __name__ == '__main__':
    DuhnList('julio@morgane.com').deed_list()
