#!/usr/bin/env python

import sys
import argparse
import datetime
import uuid

import boto3

class DuhnAdder:
    def __init__(self, email, args):
        boto3.setup_default_session(profile_name='duhnit')
        dynamodb = boto3.resource('dynamodb')
        self.deeds_table = dynamodb.Table('deeds')
        self.email = email
        self.args = args

    def detail(self, args):
        return [
            {
                'felt': self.args.felt
            },
            {
            }
        ]

    def persist_deed(self, args):
        self.deeds_table.put_item(Item={
            'author-email': self.email,
            'deed-type': '{deed_type}-{uuid}'.format(deed_type=self.args.type, uuid=uuid.uuid4()),
            'deed': self.args.deed,
            'done-at': str(datetime.datetime.now()),
            'detail': self.detail(args)
        })

    def resolve_deed(self):
        if self.args.type == 'test':
            print(args)
        else:
            self.persist_deed(args)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='What I duhn!')

    parser.add_argument('deed', type=str, help='What I duhn!')
    parser.add_argument('--felt', default='normal', help='How I felt with this deed (default: normal)')
    parser.add_argument('-t', '--type', default='test',   help='What type of deed was this (default: test)')

    args = parser.parse_args()

    DuhnAdder('julio@morgane.com', args).resolve_deed()
